#!/usr/bin/env python3
"""
generate_cometbft_config.py — Native SPS-Chain config generator.

Replaces the old evmosd/bootlab approach entirely.
Generates config.toml for every node directly in Python. No Docker bootnode
needed, no Cosmos SDK, no EVM. Runs in < 1 second.

Topology:
  Validators  : validator0 (10.99.0.1), validator1 (10.99.0.2), validator2 (10.99.0.3)
  Agents      : light0 (10.99.0.11), light1 (10.99.0.12), light2 (10.99.0.13)
  Fullnode    : fullnode0 (10.99.0.14 / 172.16.4.10)
"""

import os
import shutil
import secrets
import hashlib
import subprocess
import logging

logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")
log = logging.getLogger("sps-config-gen")

# ── Network topology ────────────────────────────────────────────────────────
VALIDATORS = {
    "validator0": "10.99.0.1",
    "validator1": "10.99.0.2",
    "validator2": "10.99.0.3",
}

AGENTS = {
    "light0": {"mgmt": "172.16.1.10", "blockchain": "10.99.0.11"},
    "light1": {"mgmt": "172.16.2.10", "blockchain": "10.99.0.12"},
    "light2": {"mgmt": "172.16.3.10", "blockchain": "10.99.0.13"},
}

FULLNODE = {
    "fullnode0": {"actuator_net": "172.16.4.10", "blockchain": "10.99.0.14"},
}

P2P_PORT  = 26656
API_PORT  = 3000
BASE_DIR  = os.path.join("lab", "cometbft")

# Attack parameters tracked by the IDS ledger
PARAMETERS = ["SQL_INJECTION", "XSS_ATTACK", "PATH_TRAVERSAL", "COMMAND_INJECTION"]
AGENTS_COUNT = 3   # majority threshold (votes > agents_count/2)

# Actuator endpoint (fullnode0 → actuator container)
ACTUATOR_URL = "http://172.16.4.1:5000/action"


# ── Key generation ──────────────────────────────────────────────────────────

def generate_node_id() -> str:
    """Generate a 40-char hex node ID (matches CometBFT style)."""
    raw = secrets.token_bytes(20)
    return raw.hex()


# ── Config TOML builder ─────────────────────────────────────────────────────

def build_config(
    node_id: str,
    role: str,
    listen_ip: str,
    peers: list[str],
    actuator_url: str = "",
) -> str:
    """Render a config.toml string for one node."""
    peer_list = ", ".join(f'"{p}"' for p in peers)

    actuator_section = ""
    if actuator_url:
        actuator_section = f"""
[actuator]
url = "{actuator_url}"
"""

    return f"""# sps-node configuration — generated by generate_cometbft_config.py

[node]
id       = "{node_id}"
role     = "{role}"
listen_addr = "0.0.0.0:{P2P_PORT}"
api_addr    = "0.0.0.0:{API_PORT}"

[consensus]
timeout_propose_ms = 200
timeout_commit_ms  = 200
block_max_txs      = 50000

[mempool]
size = 100000
max_txs_bytes = 1073741824

[ledger]
parameters   = {json_list(PARAMETERS)}
agents_count = {AGENTS_COUNT}

[peers]
persistent = [{peer_list}]
{actuator_section}
"""


def json_list(items: list[str]) -> str:
    inner = ", ".join(f'"{i}"' for i in items)
    return f"[{inner}]"


# ── Directory helpers ───────────────────────────────────────────────────────

def write_config(node_name: str, config_str: str):
    out_dir = os.path.join(BASE_DIR, node_name, "data")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "config.toml")
    with open(out_path, "w") as f:
        f.write(config_str)
    log.info("  Written: %s", out_path)


def clean_old_evmos_artifacts(node_name: str):
    """Remove stale config/, data/, keyring-test/, contract/ directories."""
    node_dir = os.path.join(BASE_DIR, node_name)
    for sub in ("data/config", "data/data", "data/keyring-test", "data/contract"):
        full = os.path.join(node_dir, sub)
        if os.path.exists(full):
            shutil.rmtree(full)
            log.debug("  Removed: %s", full)


# ── SSH key generation ──────────────────────────────────────────────────────

def generate_ssh_keys():
    ssh_dir = os.path.join(BASE_DIR, "shared", "ssh")
    key_path = os.path.join(ssh_dir, "actuator_id_ed25519")
    if os.path.exists(key_path):
        log.info("SSH keys already exist — skipping.")
        return
    os.makedirs(ssh_dir, exist_ok=True)
    log.info("Generating SSH keys for actuator...")
    subprocess.run(
        ["ssh-keygen", "-t", "ed25519", "-f", key_path, "-N", "", "-C", "actuator@sps"],
        check=True,
    )
    log.info("SSH keys generated in %s", ssh_dir)


# ── Main ────────────────────────────────────────────────────────────────────

def generate_all():
    log.info("=== SPS-Chain Config Generator ===")

    # 1. Generate a node ID for each node
    node_ids: dict[str, str] = {}
    all_nodes = (
        list(VALIDATORS.keys())
        + list(AGENTS.keys())
        + list(FULLNODE.keys())
    )
    for name in all_nodes:
        node_ids[name] = generate_node_id()
        log.info("  Node %-12s → id=%s", name, node_ids[name])

    # 2. Build persistent peers list for validators (all validators peer with each other)
    validator_peers = [
        f"{node_ids[n]}@{ip}:{P2P_PORT}"
        for n, ip in VALIDATORS.items()
    ]

    # All-node peers: validators + fullnode reachable on blockchain network
    all_blockchain_peers = validator_peers + [
        f"{node_ids['fullnode0']}@{FULLNODE['fullnode0']['blockchain']}:{P2P_PORT}",
    ]

    # 3. Write configs for validators
    for name, ip in VALIDATORS.items():
        # Validators peer with each other (exclude self)
        my_peers = [p for p in validator_peers if node_ids[name] not in p]
        cfg = build_config(node_ids[name], "validator", ip, my_peers)
        write_config(name, cfg)

    # 4. Write configs for agents (light nodes)
    for name, addrs in AGENTS.items():
        # Agents peer with all validators + fullnode
        cfg = build_config(node_ids[name], "agent", addrs["blockchain"], all_blockchain_peers)
        write_config(name, cfg)

    # 5. Write config for fullnode0
    fn_name = "fullnode0"
    fn_peers = all_blockchain_peers  # peer with all validators
    cfg = build_config(
        node_ids[fn_name], "fullnode",
        FULLNODE[fn_name]["blockchain"],
        fn_peers,
        actuator_url=ACTUATOR_URL,
    )
    write_config(fn_name, cfg)

    log.info("=== Config generation complete ===")
    log.info("Node IDs:")
    for name, nid in node_ids.items():
        log.info("  %-12s %s", name, nid)


if __name__ == "__main__":
    try:
        generate_ssh_keys()
        generate_all()
    except Exception as e:
        log.error("Config generation failed: %s", e)
        raise