# -- Untrusted Zone --
attacker[0]="untrusted"
router[0]="untrusted"

# -- DMZ --
router[1]="dmz"
juice_shop[0]="dmz"

# IDS sniffing on DMZ
ids_snort[1]="dmz"
ids_suricata[1]="dmz"
ids_zeek[1]="dmz"

# -- Management Network (IDS to Validators) --
ids_snort[0]="mgmt1"
validator0[0]="mgmt1"

ids_suricata[0]="mgmt2"
validator1[0]="mgmt2"

ids_zeek[0]="mgmt3"
validator2[0]="mgmt3"

# -- Blockchain Network --
validator0[1]="blockchain"
validator1[1]="blockchain"
validator2[1]="blockchain"

# -- Images --
juice_shop[image]="juice_shop"
attacker[image]="attacker_carbonyl"

ids_snort[image]="ids_snort"
ids_suricata[image]="ids_suricata"
ids_zeek[image]="ids_zeek"

validator0[image]="kathara/quorum"
validator1[image]="kathara/quorum"
validator2[image]="kathara/quorum"

# -- Resource Limits --
validator0[mem]="512m"
validator1[mem]="512m"
validator2[mem]="512m"