# -- Untrusted Zone --
attacker[0]="untrusted"
router[0]="untrusted"

# -- DMZ --
router[1]="dmz"
juice_shop[0]="dmz"

ids_snort[1]="dmz"
ids_suricata[1]="dmz"
ids_zeek[1]="dmz"

# -- Manager System --
ids_snort[0]="mgmt"
node1[0]="mgmt"

ids_suricata[0]="mgmt"
node2[0]="mgmt"

ids_zeek[0]="mgmt"
node3[0]="mgmt"

node1[1]="blockchain"
node2[1]="blockchain"
node3[1]="blockchain"

blockchain_mock[0]="blockchain"

# -- Images --
juice_shop[image]="juice_shop"
attacker[image]="attacker_carbonyl"

ids_snort[image]="ids_snort"
ids_suricata[image]="ids_suricata"
ids_zeek[image]="ids_zeek"

node1[image]="kathara/base"
node2[image]="kathara/base"
node3[image]="kathara/base"

blockchain_mock[image]="kathara/base"