# Rileva se 'cometbft' o 'quorum' sono stati passati come comandi
ifneq ($(filter cometbft,$(MAKECMDGOALS)),)
    LAB_TYPE := cometbft
    BASE_DIR := lab/cometbft
    ENV_VARS := PYTHONIOENCODING=utf-8 LC_ALL=C.UTF-8 LANG=C.UTF-8
else
    # Imposta Quorum come default se non viene specificato nulla o se viene passato 'quorum'
    LAB_TYPE := quorum
    BASE_DIR := lab/quorum
    ENV_VARS := PYTHONIOENCODING=utf-8 LC_ALL=C.UTF-8 LANG=C.UTF-8
endif

.PHONY: quorum cometbft build generate-config start clean clean-config test setup measure benchmark blockchain-benchmark help

quorum:
	@echo "Use make quorum 'COMMAND' to apply the command to the quorum lab"

cometbft:
	@echo "Use make cometbft 'COMMAND' to apply the command to the cometbft lab"

build:
	@echo "Building Juice Shop..."
	docker build -t juice_shop $(BASE_DIR)/juice_shop
	@echo "Building Attacker..."
	docker build -t attacker_carbonyl $(BASE_DIR)/attacker
	@echo "Building Snort..."
	docker build -t ids_snort $(BASE_DIR)/ids_snort
	@echo "Building Suricata..."
	docker build -t ids_suricata $(BASE_DIR)/ids_suricata
	@echo "Building Zeek..."
	docker build -t ids_zeek $(BASE_DIR)/ids_zeek
	@echo "Building $(LAB_TYPE) blockchain image..."
	docker build -t kathara/$(LAB_TYPE) -f $(BASE_DIR)/shared/Dockerfile $(BASE_DIR)
	@echo "Building Actuator..."
	docker build -t actuator $(BASE_DIR)/actuator

generate-config:
	@echo "Generating blockchain configuration for $(LAB_TYPE)..."
ifeq ($(LAB_TYPE),cometbft)
	$(ENV_VARS) .venv/bin/python generate_cometbft_config.py
else
	$(ENV_VARS) .venv/bin/python generate_blockchain_config.py
endif

start:
	@echo "Starting Kathara lab in $(BASE_DIR)..."
	$(ENV_VARS) kathara lstart -d $(BASE_DIR)

clean:
	@echo "Stopping Kathara lab in $(BASE_DIR)..."
	$(ENV_VARS) kathara lclean -d $(BASE_DIR)


clean-config:
	@echo "Cleaning generated files in $(BASE_DIR)..."
	kathara lclean -d $(BASE_DIR)
ifeq ($(LAB_TYPE),cometbft)
	cd $(BASE_DIR) && rm -rf validator*/data validator*/config validator*/contract validator*/keyring-test
	cd $(BASE_DIR) && rm -rf light*/data light*/config light*/contract light*/keyring-test
	cd $(BASE_DIR) && rm -rf fullnode*/data fullnode*/config fullnode*/contract fullnode*/keyring-test
	cd $(BASE_DIR) && rm -rf blockchain_config_tmp
else
	cd $(BASE_DIR) && rm -rf validator0/data validator1/data validator2/data
	cd $(BASE_DIR) && rm -rf member0/data member1/data member2/data member3/data
	cd $(BASE_DIR) && rm -rf ../resources/blockchain_configurations
endif
	cd $(BASE_DIR) && rm -rf shared/ssh
	rm -f $(BASE_DIR)/shared/contract_address.txt $(BASE_DIR)/shared/contract_abi.json
	rm -rf benchmark/__pycache__

measure:
	@echo "Measuring response time for $(LAB_TYPE)..."
	cd benchmark && $(ENV_VARS) ../.venv/bin/python measure_response_time.py ../$(BASE_DIR)

N ?= 10
chart:
	@echo "Generating chart for $(LAB_TYPE) simulating $(N) attacks..."
	cd benchmark && $(ENV_VARS) ../.venv/bin/python generate_chart.py ../$(BASE_DIR) $(N)

capacity:
	@echo "Running capacity benchmark for $(LAB_TYPE)..."
	cd benchmark && $(ENV_VARS) ../.venv/bin/python benchmark_throughput.py ../$(BASE_DIR)


blockchain-benchmark:
	@echo "Running new blockchain benchmark for $(LAB_TYPE)..."
	cd benchmark && $(ENV_VARS) ../.venv/bin/python blockchain_benchmark.py ../$(BASE_DIR)

	
setup: build generate-config start

help:
	@echo "SelfProtectingSystem Makefile"
	@echo ""
	@echo "Uso dei prefissi di ambiente:"
	@echo "  make quorum [target]   - Applica i comandi alla directory /lab/quorum"
	@echo "  make cometbft [target] - Applica i comandi alla directory /lab/cometbft"
	@echo ""
	@echo "Targets disponibili:"
	@echo "  build           - Build all Docker images"
	@echo "  generate-config - Generate blockchain configuration"
	@echo "  start           - Start the Kathara lab"
	@echo "  clean           - Stop the Kathara lab"
	@echo "  clean-config    - Clean all config files generated by generate-config script"
	@echo "  test            - Run tests"
	@echo "  measure         - Measure Lab's IDS/Actuator response time"
	@echo "  measure-verbose - Run measure response time with verbose detailed block logs"
	@echo "  chart           - Generate boxplot chart simulating N attacks (es. make chart N=10)"
	@echo "  capacity        - Run capacity benchmark (IDS + Blockchain)"
	@echo "  blockchain-benchmark - Run direct blockchain capacity benchmark (no batching)"
	@echo "  setup           - Full setup (build + config + start)"
	@echo "  help            - Show this help"

# Catch-all per ignorare argomenti extra (es. 10 in make chart 10)
%:
	@:
	