.PHONY: build generate-config start clean clean-config test

build:
	@echo "Building Juice Shop..."
	docker build -t juice_shop ./juice_shop
	@echo "Building Attacker..."
	docker build -t attacker_carbonyl ./attacker
	@echo "Building Snort..."
	docker build -t ids_snort ./ids_snort
	@echo "Building Suricata..."
	docker build -t ids_suricata ./ids_suricata
	@echo "Building Zeek..."
	docker build -t ids_zeek ./ids_zeek
	@echo "Building Quorum blockchain image..."
	docker build -t kathara/quorum -f ./shared/Dockerfile .

generate-config:
	@echo "Generating blockchain configuration..."
	.venv/bin/python generate_blockchain_config.py


start:
	@echo "Starting Kathara lab..."
	kathara lstart

clean:
	@echo "Stopping Kathara lab..."
	kathara lclean

clean-config:
	@echo "Cleaning generated files..."
	rm -rf validator0/data validator1/data validator2/data
	rm -rf blockchain_config_tmp
	rm -rf ../resources/blockchain_configurations


test:
	@echo "Running tests..."
	./tests/run_all_tests.sh
	./tests/test_attack_flow.sh
	./tests/test_blockchain_consensus.sh

setup: build generate-config start

help:
	@echo "SelfProtectingSystem Makefile"
	@echo ""
	@echo "Usage:"
	@echo "  make build           - Build all Docker images"
	@echo "  make generate-config - Generate blockchain configuration"
	@echo "  make start           - Start the Kathara lab"
	@echo "  make clean           - Stop the Kathara lab"
	@echo "  make clean-config	  - Clean all config files generated by generate-config script"
	@echo "  make test            - Run tests"
	@echo "  make setup           - Full setup (build + config + start)"
	@echo "  make help            - Show this help"