# Rileva se 'cometbft' o 'quorum' sono stati passati come comandi
ifneq ($(filter cometbft,$(MAKECMDGOALS)),)
    LAB_TYPE := cometbft
    BASE_DIR := lab/cometbft
else
    # Imposta Quorum come default se non viene specificato nulla o se viene passato 'quorum'
    LAB_TYPE := quorum
    BASE_DIR := lab/quorum
endif

.PHONY: quorum cometbft build generate-config start clean clean-config test setup help

# Target fittizi per catturare la variabile senza che 'make' dia errore
quorum:
	@echo "--> Ambiente impostato su: Quorum ($(BASE_DIR))"

cometbft:
	@echo "--> Ambiente impostato su: CometBFT ($(BASE_DIR))"

build:
	@echo "Building Juice Shop..."
	docker build -t juice_shop $(BASE_DIR)/juice_shop
	@echo "Building Attacker..."
	docker build -t attacker_carbonyl $(BASE_DIR)/attacker
	@echo "Building Snort..."
	docker build -t ids_snort $(BASE_DIR)/ids_snort
	@echo "Building Suricata..."
	docker build -t ids_suricata $(BASE_DIR)/ids_suricata
	@echo "Building Zeek..."
	docker build -t ids_zeek $(BASE_DIR)/ids_zeek
	@echo "Building $(LAB_TYPE) blockchain image..."
	docker build -t kathara/$(LAB_TYPE) -f $(BASE_DIR)/shared/Dockerfile $(BASE_DIR)
	@echo "Building Actuator..."
	docker build -t actuator $(BASE_DIR)/actuator

generate-config:
	@echo "Generating blockchain configuration for $(LAB_TYPE)..."
	.venv/bin/python generate_blockchain_config.py

start:
	@echo "Starting Kathara lab in $(BASE_DIR)..."
	kathara lstart -d $(BASE_DIR)

clean:
	@echo "Stopping Kathara lab in $(BASE_DIR)..."
	kathara lclean -d $(BASE_DIR)

clean-config:
	@echo "Cleaning generated files in $(BASE_DIR)..."
	kathara lclean -d $(BASE_DIR)
	cd $(BASE_DIR) && rm -rf validator0/data validator1/data validator2/data
	cd $(BASE_DIR) && rm -rf member0/data member1/data member2/data member3/data
	cd $(BASE_DIR) && rm -rf blockchain_config_tmp
	cd $(BASE_DIR) && rm -rf ../resources/blockchain_configurations
	cd $(BASE_DIR) && rm -rf shared/ssh
	rm -f $(BASE_DIR)/shared/contract_address.txt $(BASE_DIR)/shared/contract_abi.json

test:
	@echo "Running tests for $(LAB_TYPE)..."
	cd $(BASE_DIR) && ./tests/test_loop.sh

setup: build generate-config start

help:
	@echo "SelfProtectingSystem Makefile"
	@echo ""
	@echo "Uso dei prefissi di ambiente:"
	@echo "  make quorum [target]   - Applica i comandi alla directory /lab/quorum"
	@echo "  make cometbft [target] - Applica i comandi alla directory /lab/cometbft"
	@echo ""
	@echo "Targets disponibili:"
	@echo "  build           - Build all Docker images"
	@echo "  generate-config - Generate blockchain configuration"
	@echo "  start           - Start the Kathara lab"
	@echo "  clean           - Stop the Kathara lab"
	@echo "  clean-config    - Clean all config files generated by generate-config script"
	@echo "  test            - Run tests"
	@echo "  setup           - Full setup (build + config + start)"
	@echo "  help            - Show this help"