FROM kathara/base

RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    libnss3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L -o /tmp/carbonyl.zip https://github.com/fathyb/carbonyl/releases/download/v0.0.3/carbonyl.linux-amd64.zip \
    && unzip /tmp/carbonyl.zip -d /opt/ \
    && rm /tmp/carbonyl.zip

RUN ln -s /opt/carbonyl-0.0.3/carbonyl /usr/bin/carbonyl