# -- Zona Non Fidata (Untrusted) --
attacker[0]="untrusted"
router[0]="untrusted"

# -- Zona DMZ --
router[1]="dmz"
juice_shop[0]="dmz"

# IDS in ascolto sulla DMZ (sniffing)
ids_snort[1]="dmz"
ids_suricata[1]="dmz"
ids_zeek[1]="dmz"

# -- Rete di Management (da IDS a Light Node) --
ids_snort[0]="mgmt1"
light0[0]="mgmt1"   

ids_suricata[0]="mgmt2"
light1[0]="mgmt2"

ids_zeek[0]="mgmt3"
light2[0]="mgmt3"

# -- Rete Attuatore --
fullnode0[0]="actuator_net"
actuator[0]="actuator_net"
actuator[1]="dmz"

# -- Rete di Feedback --
actuator[2]="feedback"
ids_snort[2]="feedback"
ids_suricata[2]="feedback"
ids_zeek[2]="feedback"

# -- Rete Blockchain --
validator0[0]="blockchain"
validator1[0]="blockchain"
validator2[0]="blockchain"
light0[1]="blockchain"
light1[1]="blockchain"
light2[1]="blockchain"
fullnode0[1]="blockchain"

# -- Immagini Docker --
juice_shop[image]="juice_shop"
attacker[image]="attacker_carbonyl"

ids_snort[image]="ids_snort"
ids_suricata[image]="ids_suricata"
ids_zeek[image]="ids_zeek"

validator0[image]="kathara/cometbft"
validator1[image]="kathara/cometbft"
validator2[image]="kathara/cometbft"

light0[image]="kathara/cometbft"
light1[image]="kathara/cometbft"
light2[image]="kathara/cometbft"
fullnode0[image]="kathara/cometbft"

actuator[image]="actuator"

wireshark[bridged]=true
wireshark[port]="3000:3000"
wireshark[image]="lscr.io/linuxserver/wireshark"
wireshark[num_terms]=0
