/// IDS voting state machine — pure Rust reimplementation of IDS.sol.
/// Thread-safe via caller-held lock (the struct itself is not Sync).
use std::collections::HashMap;
use std::path::Path;
use sha2::{Sha256, Digest};
use crate::types::ActionEvent;


#[derive(Debug, Default)]
struct ParamStatus {
    current_value: u64,
    agent_proposed: HashMap<String, u64>, // agent_id -> proposed value
    vote_count: HashMap<u64, usize>,      // value -> number of votes
    has_voted: HashMap<String, bool>,     // agent_id -> has ever voted
}

pub struct Ledger {
    parameters: Vec<String>,
    status_map: HashMap<String, ParamStatus>,
    state_action: HashMap<String, String>, // sha256(state_str) -> action
    agents_count: usize,
    committed_txs: u64,
    pub dedup_disabled: bool,
}

impl Ledger {
    pub fn new(parameters: Vec<String>, agents_count: usize) -> Self {
        let mut status_map = HashMap::new();
        for p in &parameters {
            status_map.insert(p.clone(), ParamStatus::default());
        }
        Self {
            parameters,
            status_map,
            state_action: HashMap::new(),
            agents_count,
            committed_txs: 0,
            dedup_disabled: false,
        }
    }

    /// Build the 4-bit state → action map.
    /// Mirrors the policy generated by populate_action_map.js.
    pub fn populate_action_map(&mut self) {
        // We map parameters to bits in REVERSE order of the parameters list.
        // For ["SAFE", "SQL", "XSS", "PATH", "CMD"]:
        // CMD = bit 0 (1), PATH = bit 1 (2), XSS = bit 2 (4), SQL = bit 3 (8), SAFE = bit 4 (16)
        let n = self.parameters.len();
        let max_val = (1 << n) - 1;

        for i in 1..=max_val {
            let mut actions = Vec::new();
            let mut state_bits = Vec::new();

            for (idx, param) in self.parameters.iter().enumerate() {
                let bit_pos = n - 1 - idx;
                let bit_val = 1 << bit_pos;
                let is_set = (i & bit_val) != 0;
                
                state_bits.push(if is_set { "1" } else { "0" });

                if is_set {
                    match param.as_str() {
                        "SQL_INJECTION" => actions.push("echo SQL Injection detected"),
                        "XSS_ATTACK" => actions.push("echo XSS Attack detected"),
                        "PATH_TRAVERSAL" => actions.push("echo Path Traversal detected"),
                        "COMMAND_INJECTION" => actions.push("echo Command Injection detected"),
                        _ => {}
                    }
                }
            }

            let state_str: String = state_bits.concat();
            let action_str = actions.join(" && ");
            
            if !action_str.is_empty() {
                let hash = hex::encode(Sha256::digest(state_str.as_bytes()));
                self.state_action.insert(hash, action_str);
            }
        }
        log::info!("[LEDGER] Action map ready — {} entries", self.state_action.len());
    }

    /// Process a vote from an agent. Returns ActionEvent if a new action is triggered.
    /// Mirrors IDS.sol::proposeNewValues exactly.
    pub fn propose_new_values(
        &mut self,
        agent_id: &str,
        parameters: &[String],
        values: &[u64],
    ) -> Option<ActionEvent> {
        let dedup_disabled = self.dedup_disabled;
        let mut changed = false;
        let mut has_effective_vote = false;

        for (param, &new_value) in parameters.iter().zip(values.iter()) {
            let status = match self.status_map.get_mut(param.as_str()) {
                Some(s) => s,
                None => {
                    log::debug!("[LEDGER] Unknown param: {}", param);
                    continue;
                }
            };

            // If the agent has already voted for this parameter, decrement the count of the previous vote.
            if let Some(&previous_vote) = status.agent_proposed.get(agent_id) {
                if previous_vote == new_value && !dedup_disabled {
                    continue;
                }
                if let Some(count) = status.vote_count.get_mut(&previous_vote) {
                    if *count > 0 {
                        *count -= 1;
                    }
                }
            } else {
                status.has_voted.insert(agent_id.to_string(), true);
            }

            // Record the new vote and increment its count
            status.agent_proposed.insert(agent_id.to_string(), new_value);
            *status.vote_count.entry(new_value).or_insert(0) += 1;
            
            has_effective_vote = true;

            let votes = *status.vote_count.get(&new_value).unwrap();
            let threshold = self.agents_count / 2;
            
            log::debug!("[LEDGER] {} check | Value: {} | Votes: {} | Threshold: {}", param, new_value, votes, threshold);

            if votes > threshold && status.current_value != new_value {
                log::info!(
                    "[LEDGER] MAJORITY MET for {} ({} -> {})! {}/{} votes",
                    param, status.current_value, new_value, votes, self.agents_count
                );
                status.current_value = new_value;
                changed = true;
            }
        }

        if !has_effective_vote {
            return None;
        }

        self.committed_txs += 1;

        if changed {
            // Build binary state string from parameter values
            let state_str: String = self.parameters.iter()
                .map(|p| self.status_map[p].current_value.to_string())
                .collect();
            let hash = hex::encode(Sha256::digest(state_str.as_bytes()));

            if let Some(action) = self.state_action.get(&hash) {
                let ts = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_millis() as u64;
                log::info!("[LEDGER] ActionRequired: state={} action={}", state_str, action);
                return Some(ActionEvent {
                    action: action.clone(),
                    state: state_str,
                    timestamp_ms: ts,
                });
            }
        }
        None
    }

    pub fn tx_count(&self) -> u64 { self.committed_txs }

    pub fn get_state(&self) -> String {
        self.parameters.iter()
            .map(|p| self.status_map[p].current_value.to_string())
            .collect()
    }

    pub fn get_votes(&self) -> serde_json::Value {
        let mut res = serde_json::Map::new();
        for (param, status) in &self.status_map {
            let mut votes = serde_json::Map::new();
            for (val, count) in &status.vote_count {
                votes.insert(val.to_string(), serde_json::json!(count));
            }
            res.insert(param.clone(), serde_json::Value::Object(votes));
        }
        serde_json::Value::Object(res)
    }
}
