/// IDS voting state machine — pure Rust reimplementation of IDS.sol.
/// Thread-safe via caller-held lock (the struct itself is not Sync).
use std::collections::HashMap;
use std::path::Path;
use sha2::{Sha256, Digest};
use crate::types::ActionEvent;

const DISABLE_LEDGER_DEDUP_MARKER: &str = "/shared/disable_ledger_dedup";

#[derive(Debug, Default)]
struct ParamStatus {
    current_value: u64,
    agent_proposed: HashMap<String, u64>, // agent_id -> proposed value
    vote_count: HashMap<u64, usize>,      // value -> number of votes
    has_voted: HashMap<String, bool>,     // agent_id -> has ever voted
}

pub struct Ledger {
    parameters: Vec<String>,
    status_map: HashMap<String, ParamStatus>,
    state_action: HashMap<String, String>, // sha256(state_str) -> action
    agents_count: usize,
    committed_txs: u64,
}

impl Ledger {
    pub fn new(parameters: Vec<String>, agents_count: usize) -> Self {
        let mut status_map = HashMap::new();
        for p in &parameters {
            status_map.insert(p.clone(), ParamStatus::default());
        }
        Self {
            parameters,
            status_map,
            state_action: HashMap::new(),
            agents_count,
            committed_txs: 0,
        }
    }

    /// Build the 4-bit state → action map.
    /// Mirrors the policy generated by populate_action_map.js.
    pub fn populate_action_map(&mut self) {
        // bit mapping: SQL_INJECTION=8, XSS=4, PATH_TRAVERSAL=2, COMMAND_INJECTION=1
        let base: &[(u8, &str)] = &[
            (8, "echo SQL Injection detected"),
            (4, "echo XSS Attack detected"),
            (2, "echo Path Traversal detected"),
            (1, "echo Command Injection detected"),
        ];
        for i in 1u8..=15u8 {
            let state_str = format!("{:04b}", i);
            let action: Vec<&str> = base.iter()
                .filter(|(bit, _)| (i & bit) == *bit)
                .map(|(_, a)| *a)
                .collect();
            let action_str = action.join(" && ");
            let hash = hex::encode(Sha256::digest(state_str.as_bytes()));
            self.state_action.insert(hash, action_str);
        }
        log::info!("[LEDGER] Action map ready — {} entries", self.state_action.len());
    }

    /// Process a vote from an agent. Returns ActionEvent if a new action is triggered.
    /// Mirrors IDS.sol::proposeNewValues exactly.
    pub fn propose_new_values(
        &mut self,
        agent_id: &str,
        parameters: &[String],
        values: &[u64],
    ) -> Option<ActionEvent> {
        let dedup_disabled = Path::new(DISABLE_LEDGER_DEDUP_MARKER).exists();
        let mut changed = false;
        let mut has_effective_vote = false;

        for (param, &new_value) in parameters.iter().zip(values.iter()) {
            let status = match self.status_map.get_mut(param.as_str()) {
                Some(s) => s,
                None => {
                    log::debug!("[LEDGER] Unknown param: {}", param);
                    continue;
                }
            };

            // Native throughput benchmark can disable state-based dedup to measure raw vote ingestion.
            if !dedup_disabled && status.current_value == new_value {
                continue;
            }

            if *status.has_voted.get(agent_id).unwrap_or(&false) {
                let prev = *status.agent_proposed.get(agent_id).unwrap_or(&0);
                if !dedup_disabled && prev == new_value {
                    continue; // No change
                }
                // Decrement previous vote
                if let Some(cnt) = status.vote_count.get_mut(&prev) {
                    if *cnt > 0 { *cnt -= 1; }
                }
            } else {
                status.has_voted.insert(agent_id.to_string(), true);
            }

            has_effective_vote = true;

            status.agent_proposed.insert(agent_id.to_string(), new_value);
            *status.vote_count.entry(new_value).or_insert(0) += 1;

            // Majority check: voteCount > agents_count / 2
            let votes = *status.vote_count.get(&new_value).unwrap_or(&0);
            if votes > (self.agents_count / 2) && status.current_value != new_value {
                status.current_value = new_value;
                changed = true;
            }
        }

        if !has_effective_vote {
            return None;
        }

        self.committed_txs += 1;

        if changed {
            // Build binary state string from parameter values
            let state_str: String = self.parameters.iter()
                .map(|p| self.status_map[p].current_value.to_string())
                .collect();
            let hash = hex::encode(Sha256::digest(state_str.as_bytes()));

            if let Some(action) = self.state_action.get(&hash) {
                let ts = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_millis() as u64;
                log::info!("[LEDGER] ActionRequired: state={} action={}", state_str, action);
                return Some(ActionEvent {
                    action: action.clone(),
                    state: state_str,
                    timestamp_ms: ts,
                });
            }
        }
        None
    }

    pub fn tx_count(&self) -> u64 { self.committed_txs }
}
