#--UntrustedZone--
attacker[0]="untrusted"
router[0]="untrusted"

#--DMZ--
router[1]="dmz"
juice_shop[0]="dmz"

#IDSsniffingonDMZ
ids_snort[1]="dmz"
ids_suricata[1]="dmz"
ids_zeek[1]="dmz"

#--ManagementNetwork(IDStoMemberNodes)--
ids_snort[0]="mgmt1"
member0[0]="mgmt1"

ids_suricata[0]="mgmt2"
member1[0]="mgmt2"

ids_zeek[0]="mgmt3"
member2[0]="mgmt3"

#--ActuatorNetwork--
member3[0]="actuator_net"
actuator[0]="actuator_net"
actuator[1]="dmz"

#--Feedbacknetwork--
actuator[2]="feedback"
ids_snort[2]="feedback"
ids_suricata[2]="feedback"
ids_zeek[2]="feedback"

#--BlockchainNetwork--
validator0[0]="blockchain"
validator1[0]="blockchain"
validator2[0]="blockchain"
member0[1]="blockchain"
member1[1]="blockchain"
member2[1]="blockchain"
member3[1]="blockchain"

#--Images--
juice_shop[image]="juice_shop"
attacker[image]="attacker_carbonyl"

ids_snort[image]="ids_snort"
ids_suricata[image]="ids_suricata"
ids_zeek[image]="ids_zeek"

validator0[image]="kathara/quorum"
validator1[image]="kathara/quorum"
validator2[image]="kathara/quorum"

member0[image]="kathara/quorum"
member1[image]="kathara/quorum"
member2[image]="kathara/quorum"
member3[image]="kathara/quorum"

actuator[image]="actuator"

wireshark[bridged]=true
wireshark[port]="3000:3000"
wireshark[image]="lscr.io/linuxserver/wireshark"
wireshark[num_terms]=0

attacker[num_terms]=0
actuator[num_terms]=0
member0[num_terms]=0
member1[num_terms]=0
member2[num_terms]=0
member3[num_terms]=0
validator0[num_terms]=0
validator1[num_terms]=0
validator2[num_terms]=0
ids_zeek[num_terms]=0
ids_suricata[num_terms]=0
ids_snort[num_terms]=0
router[num_terms]=0
juice_shop[num_terms]=0


